module.exports = {
  apps: [
    {
      name: 'worker-primary',
      script: 'workers/worker-manager.ts',
      interpreter: 'node',
      interpreter_args: '--require tsx/cjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        WORKER_INSTANCE: 'primary',
      },
      error_file: './logs/worker-primary-error.log',
      out_file: './logs/worker-primary-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'worker-backup',
      script: 'workers/worker-manager.ts',
      interpreter: 'node',
      interpreter_args: '--require tsx/cjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        WORKER_INSTANCE: 'backup',
      },
      error_file: './logs/worker-backup-error.log',
      out_file: './logs/worker-backup-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
}
