
import React from "react";
import { TemplateProps } from "./RestaurantTemplate";

export default function ModernMinimalTemplate({
  content,
  leadInfo,
}: TemplateProps) {
  return (
    <div className="min-h-screen bg-white text-black font-mono selection:bg-lime-300">
      <header className="p-6 md:p-12 flex justify-between items-center border-b-2 border-black">
        <h1 className="text-2xl md:text-4xl font-black tracking-tighter uppercase">
          {leadInfo?.business_name || "AGENCY"}
        </h1>
        <div className="flex items-center gap-2">
          <span className="w-3 h-3 bg-lime-400 rounded-full animate-pulse border border-black"></span>
          <span className="text-xs font-bold uppercase hidden md:inline">
            Available for work
          </span>
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-6 md:p-24 border-x-2 border-black min-h-screen">
        <div className="mb-24">
          <h2 className="text-6xl md:text-9xl font-black mb-12 leading-[0.8] tracking-tighter uppercase break-words">
            {content.hero?.headline || "WE BUILD FUTURE."}
          </h2>
          <p className="text-xl md:text-3xl font-medium max-w-3xl leading-tight">
            {content.hero?.subheadline ||
              "Minimalist design for maximum impact. We focus on what matters: your content and your growth."}
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-12 text-lg border-t-2 border-black pt-12">
          <div className="space-y-6">
            <h3 className="text-xl font-bold uppercase bg-black text-white inline-block px-2">
              Services
            </h3>
            <ul className="space-y-4 text-xl">
              <li className="flex justify-between border-b border-neutral-300 pb-2">
                <span>01. Strategy</span> <span>→</span>
              </li>
              <li className="flex justify-between border-b border-neutral-300 pb-2">
                <span>02. Design</span> <span>→</span>
              </li>
              <li className="flex justify-between border-b border-neutral-300 pb-2">
                <span>03. Development</span> <span>→</span>
              </li>
            </ul>
          </div>
          <div className="flex flex-col justify-between">
            <p className="text-neutral-500">
              We strip away the non-essential. Our approach is direct, bold, and
              effective.
            </p>
            <button className="mt-8 w-full bg-lime-400 border-2 border-black text-black py-6 text-xl font-bold hover:bg-lime-500 hover:translate-x-1 hover:-translate-y-1 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              START PROJECT
            </button>
          </div>
        </div>

        <div className="mt-40 pt-12 border-t-2 border-black flex justify-between text-xs font-bold uppercase opacity-50">
          <p>SYSTEM GENERATED BY MVP AGENCY</p>
          <p>{new Date().getFullYear()}</p>
        </div>
      </main>
    </div>
  );
}
