import { notFound } from 'next/navigation'
import { getById } from '@/lib/db'
import type { Site } from '@/types'
import ServiceBusinessTemplate from '@/templates/ServiceBusinessTemplate'
import RestaurantTemplate from '@/templates/RestaurantTemplate'
import RetailTemplate from '@/templates/RetailTemplate'
import ProfessionalTemplate from '@/templates/ProfessionalTemplate'
import ModernMinimalTemplate from '@/templates/ModernMinimalTemplate'

export const dynamic = 'force-dynamic'

interface PreviewPageProps {
  params: Promise<{
    siteId: string
  }>
}

export default async function PreviewPage({ params }: PreviewPageProps) {
  const { siteId } = await params

  // Fetch site from database
  const { data: site, error } = await getById<Site>('sites', siteId)

  if (error || !site) {
    notFound()
  }

  // Get content data
  const content = site.content_data as any

  if (!content) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">No Content Available</h1>
          <p className="text-gray-600">This site has no content data.</p>
        </div>
      </div>
    )
  }

  // Render the appropriate template based on site.style
  const renderTemplate = () => {
    const props = {
      businessName: content.businessName,
      industry: content.industry,
      heroHeadline: content.heroHeadline,
      heroSubheadline: content.heroSubheadline,
      services: content.services || [],
      about: content.about,
      cta: content.cta,
      colors: content.colors,
      logoUrl: content.logoUrl,
    }

    switch (site.style) {
      case 'service':
        return <ServiceBusinessTemplate {...props} />
      case 'restaurant':
        return <RestaurantTemplate {...props} />
      case 'retail':
        return <RetailTemplate {...props} />
      case 'professional':
        return <ProfessionalTemplate {...props} />
      case 'modern':
      default:
        return <ModernMinimalTemplate {...props} />
    }
  }

  return (
    <div className="relative">
      {renderTemplate()}

      {/* Generated by badge */}
      <div className="fixed bottom-4 right-4 bg-black/80 text-white px-4 py-2 rounded-lg shadow-lg text-sm">
        Generated by MVP Web Agency
      </div>
    </div>
  )
}
